### ISSUE TITLE
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。

### ISSUE THREAD

**Issue by ritou11** [duanqn/learn-autodown#7]
## 问题描述
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: '微机原理与应用(0)(2016-2017秋季学期)\\Homework\\\t迟交的实现 项目设计报告迟交'
文件名开头有\t，需要去除。
## 建议
https://github.com/duanqn/learn-autodown/blob/c9d2bb5cb9924d43c9aa9b77b8cddfed7ec08e37/learn.py#L270 
ele.text --> ele.text.strip()

**Comment by duanqn** [comment]
Hi,
Sorry I can't type Chinese right now. Please check if the commit on branch `whitespace` solves your problem.
Thank you for reporting this issue.

duanqn
